apiVersion: v1
kind: Pod
metadata:
  name: server-1
  labels:
    app: red
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "server"
      effect: "NoSchedule"