apiVersion: v1
kind: Pod
metadata:
  name: server-1
  labels:
    app: red
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx

      resources:
        requests:
          cpu: 0.5
          memory: "512M"
        limits:
          cpu: 1
          memory: "1G"
  nodeSelector:
      size: large