apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: deploy
    env: production
spec:
  selector:
    matchLabels:
      env: production
  replicas: 5
  template:
    metadata:
      name: local-server
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx:1.18