apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
spec:
  selector:
    matchLabels:
      name: busybox-pod
  replicas: 5
  template:
    metadata:
      labels:
        name: busybox-pod
    spec:
      containers:
        - name: busybox
          image: busybox