apiVersion: v1
kind: Pod
metadata:
  name: local-server
  labels:
    env: production
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox