apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
  labels:
    type: frontend
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 3
  template:
    metadata:
      name: server-pod
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx